config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'registrations' }
  resources :users, only: [:show]
  resources :rooms, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      delete :delete_image_attachment
    end
    resources :reservations, only: [:create]
  end
  resources :reviews, only: [:create, :destroy]
  get '/trips' => 'reservations#trips'
  get '/reservations' => 'reservations#current_reservations'
end

app/views/shared/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Airbnb_Logo_B%C3%A9lo.svg/512px-Airbnb_Logo_B%C3%A9lo.svg.png" >
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Home", root_path, class: "navbar-item" %>
    </div>

    <div class="navbar-end">
    <div class="navbar-item">
      <%= link_to "Become a host", new_room_path, class: "button is-primary has-text-white has-text-weight-bold" %>
    </div>
      <div class="navbar-item">
        <div class="buttons">
        <% if !user_signed_in? %>
          <%= link_to "Sign Up", new_user_registration_path, class: "button is-primary has-text-white" %>
          <%= link_to "Login", new_user_session_path, class: "button is-light" %>
        <% else %>
          <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            <figure class="image is-24x24">
              <%= image_tag  avatar_url(current_user), class: "is-rounded" %>
            </figure> &nbsp;
            <%= current_user.fullname %>
          </a>

          <div class="navbar-dropdown">
            <%= link_to "Your Listings", rooms_path, class: "navbar-item" %>
            <%= link_to "Your Reservations", reservations_path, class: "navbar-item" %>
            <%= link_to "Your Trips", trips_path, class: "navbar-item" %>
            <hr class="navbar-divider">
            <%= link_to "Edit Profile", edit_user_registration_path, class: "navbar-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "navbar-item" %>
          </div>
        </div>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>
<script>
$(document).ready(function() {

  // Check for click events on the navbar burger icon
  $(".navbar-burger").click(function() {

      // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
      $(".navbar-burger").toggleClass("is-active");
      $(".navbar-menu").toggleClass("is-active");

  });
});
</script>