config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'registrations' }
  resources :users, only: [:show]
  resources :rooms, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      delete :delete_image_attachment
    end
    resources :reservations, only: [:create]
  end
  resources :reviews, only: [:create, :destroy]
  get '/trips' => 'reservations#trips'
  get '/reservations' => 'reservations#current_reservations'
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :delete_all

  has_many :guest_reviews

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :home_type, presence: true
  validates :room_type, presence: true
  validates :accommodate, presence: true
  validates :bed_room, presence: true
  validates :bath_room, presence: true
  validates :room_pictures, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..5.megabytes }
  has_many_attached :room_pictures, dependent: :delete_all

  def average_rating
    guest_reviews.count == 0 ? 0 : guest_reviews.average(:star).round(2).to_i
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, except: [:index, :new, :create, :delete_image_attachment]
  before_action :authenticate_user!, except: [:show]
  def index
    @rooms = current_user.rooms
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      redirect_to listing_room_path(@room), notice: "New room created successfully!"
    else
      render :new, notice: "Something didn't work..."
    end
  end

  def show
    @reviews = Review.joins(:reservation).where(reservations: {room_id: @room.id})
  end

  def update
    if @room.update(room_params)
      flash[:notice] = "Room updated successfully"
    else
      flash[:notice] = "Something didn't work..."
    end
    redirect_back(fallback_location: request.referer)
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to rooms_path
  end
  
  def preload
    today = Date.today
    reservations = @room.reservations.select("start_date, end_date").where("start_date >= ? OR end_date >= ?", today, today)

    render json: reservations
  end

  def listing
  end

  def pricing
  end

  def description
  end

  def photo_upload
  end

  def delete_image_attachment
    image_to_delete = ActiveStorage::Attachment.find(params[:id])
    if image_to_delete.purge
      flash[:notice] = "Image successfully deleted"
    else
      flash[:notice] = "Something didn't work..."
    end
    redirect_back(fallback_location: request.referer)
  end

  def amenities
  end

  def location
  end

  private
    def set_room
      @room = Room.find(params[:id])
    end

    def room_params
      params.require(:room).permit(:home_type, :room_type, :accommodate, :bed_room, :bath_room, :listing_name, :summary, :address, :is_tv, :is_kitchen, :is_air, :is_heating, :is_internet, :price, :active, :room_pictures)
    end
end

app/helpers/room_helper.rb
module RoomHelper
    def is_done(fields = nil)
        return "<span class='icon is-right has-text-success'><i class='fa fa-check'></i></span>".html_safe if !fields
        fields.each do |field|
            return if field.blank?
        end
        "<span class='icon is-right has-text-success'><i class='fa fa-check'></i></span>".html_safe
    end

    def is_publishable(room)
        return !room.price.blank? && !room.listing_name.blank? && !room.summary.blank? && !room.room_pictures.blank? && !room.address.blank? 
    end
end

app/views/rooms/_reservation_form.html.erb
<div class="sticky">
<%= form_for([@room, @room.reservations.new]) do |f| %>
<div class="card">
            <div class="card-content">
                <p><span class="is-size-5 has-text-weight-semibold"><%= @room.price %> €</span> per night</p>
                <hr>
                <div class="field is-horizontal">
                <div class="field-label is-normal">
                    <label class="label">Dates</label>
                </div>
                <div class="field-body">
                    <div class="field">
                    
                    <div class="control is-expanded">
                    <%= f.text_field :start_date, placeholder: "From", class: "input", onChange: "changePrices()", required: true, autocomplete: 'off' %>                        
                    </div>
                    </div>

                    <div class="field">
                    <p class="control is-expanded">
                        <%= f.text_field :end_date, placeholder: "To", class: "input", onChange: "changePrices()", required: true, disabled: true, autocomplete: 'off' %>
                    </p>
                    </div>
                </div>
                </div>
                <div class="field is-horizontal">
                <div class="field-label is-normal">
                    <label class="label">Guests</label>
                </div>
                <div class="field-body">
                    <div class="field">
                    <p class="select">
                    <%= f.select :guests, (1..@room.accommodate).map {|i| [pluralize(i, "guest"),i] }%> 
                    </p>
                    </div>
                </div>
                </div> 
                <div class="columns is-mobile is-marginless">
                    <div class="column is-half has-text-left">
                        <span id="price"><%= @room.price %></span>€ x <span id="nights">1</span> nights
                    </div>
                    <div class="column is-half has-text-right">
                        <span id="total_room_price"><%= @room.price %></span>€
                    </div>
                </div>
                <hr class="is-marginless">
                <div class="columns is-mobile is-marginless">
                    <div class="column is-half has-text-left">
                        Cleaning fees
                    </div>
                    <div class="column is-half has-text-right">
                        <span id="cleaning_fees"><%= (@room.price / 10).round %></span>€
                    </div>
                </div>
                <hr class="is-marginless">
                <div class="columns is-mobile is-marginless">
                    <div class="column is-half has-text-left has-text-weight-semibolt">
                        Total
                    </div>
                    <div class="column is-half has-text-right">
                        <span id="total_price"><%= (@room.price * 1.1).round %></span>€
                    </div>
                </div>
                <%= f.submit "Book Now", class: "button is-medium is-fullwidth is-link has-text-white" %>
            </div>
            <%
=begin%>
 <footer class="card-footer">
                <p class="card-footer-item">
                <span>
                    View on <a href="https://twitter.com/codinghorror/status/506010907021828096">Twitter</a>
                </span>
                </p>
                <p class="card-footer-item">
                <span>
                    Share on <a href="#">Facebook</a>
                </span>
                </p>
            </footer> 
<%
=end%>
</div>
<% end %>
</div>

<script>
    function isEmpty(str) {
        return (!str || 0 === str.length);
    }

    function daysBetween(StartDate, EndDate) {
        const oneDay = 1000 * 60 * 60 * 24;
        const start = Date.UTC(EndDate.getFullYear(), EndDate.getMonth(), EndDate.getDate());
        const end = Date.UTC(StartDate.getFullYear(), StartDate.getMonth(), StartDate.getDate());
        return (start - end) / oneDay;
    }

    function changeDateFormat(datestr) {
        return (datestr.substr(3, 2)+"-"+datestr.substr(0, 2)+"-"+datestr.substr(6, 4));
    }

    function changePrices() {
        console.log("started")
        var start_date = changeDateFormat($("#reservation_start_date").val());
        var end_date = changeDateFormat($("#reservation_end_date").val());
        // console.log(Date.parse(changeDateFormat(start_date)));
        // console.log(Date.parse(changeDateFormat(end_date)));

        if (!isNaN(Date.parse(start_date)) && !isNaN(Date.parse(end_date)))
        {
            console.log("ici");            
            start_date = new Date(start_date);
            end_date = new Date(end_date);
            var nights = daysBetween(start_date, end_date);
            if (nights < 1) {
                nights = 1;
            }

            const price = parseInt($('#price').text())
            $('#nights').text(String(nights));
            $('#total_room_price').text(String(nights * price));
            $('#cleaning_fees').text(String(Math.round((nights * price)*0.1)));
            $('#total_price').text(String(Math.round((nights * price)*1.1)))
        }
    };
     var unavailableDates = [];
     var startDateReservations = [];
    function checkDate(date) {
        dny = date.getDate() + "-" + (date.getMonth() + 1) + "-" + date.getFullYear();
        return [$.inArray(dny, unavailableDates) == -1];
    }

    function maximumDate(date) {
        for(let i = 0; i < startDateReservations.length; i++) {
            if (date < startDateReservations[i]) {
                return startDateReservations[i]
            }
        }
        var newDate = new Date();
        // newDate.setYear(date.getYear())
        newDate.setMonth(date.getMonth() + 3 )
        newDate.setDate(date.getDate())
        console.log(newDate)
        return newDate
    }

    $(function() {
       
        $.ajax({
            url: '<%= preload_room_path(@room) %>',
            dataType: 'json',
            success: function(data) {
                $.each(data, function(arrID, arrValue) {
                    for(var d = new Date(arrValue.start_date); d <= new Date(arrValue.end_date); d.setDate(d.getDate() + 1)) {
                       unavailableDates.push($.datepicker.formatDate('d-m-yy', d));
                    }
                    startDateReservations.push(new Date(arrValue.start_date));
                })
                startDateReservations.sort(function(a,b) {
                    return a - b;
                });
            }
        })
        $.datepicker.setDefaults({
                changeMonth: true,
                dateFormat: 'dd-mm-yy'});
            $('#reservation_start_date').datepicker({
                minDate: '+0',
                beforeShowDay: checkDate,
                onSelect: function(dateStr) {
                    changePrices();
                    var date = $(this).datepicker('getDate');
                    var min = $(this).datepicker('getDate') || new Date(); // Selected date or today if none               
                    var max = maximumDate(min);

                    $('#reservation_end_date').datepicker('option', {minDate: min, maxDate: max});
                    $('#reservation_end_date').attr("disabled", false);
                }
            });
            $('#reservation_end_date').datepicker({
                minDate: '+0',
                maxDate: '+1m',
                beforeShowDay: checkDate,
                onSelect: function(dateStr) {
                    changePrices();
                    var max = $(this).datepicker('getDate'); // Selected date or null if none
                    $('#reservation_start_date').datepicker('option', {maxDate: max});
                }
            });

    })
</script>

app/views/rooms/_room_menu.html.erb
<aside class="menu">
  <ul class="menu-list">
    <li class="control has-icons-right"> <%= link_to "Listing", listing_room_path %> <%= is_done() %></li>
    <li class="control has-icons-right"> <%= link_to "Pricing", pricing_room_path %> <%= is_done([@room.price]) %> </li>
    <li class="control has-icons-right"> <%= link_to "Description", description_room_path %> <%= is_done([@room.listing_name, @room.summary]) %> </li>
    <li class="control has-icons-right"> <%= link_to "Photos", photo_upload_room_path %> <%= is_done([@room.room_pictures]) %> </li>
    <li class="control has-icons-right"> <%= link_to "Amenities", amenities_room_path %> <%= is_done() %> </li>
    <li class="control has-icons-right"> <%= link_to "Location", location_room_path %> <%= is_done([@room.address]) %> </li>
  </ul>

  <% if !is_publishable(@room) && !@room.active %>
    <%= link_to "Publish", root_path , disabled: true, class: "button is-primary has-text-white is-fullwidth" %>
  <% elsif @room.active %>
    <%= form_for @room do |f| %>
      <%= f.hidden_field :active, value: false %>
      <%= f.submit "Unpublish", class: "button is-danger has-text-white is-fullwidth" %>
    <% end %>
  <% else %>
    <%= form_for @room do |f| %>
      <%= f.hidden_field :active, value: true %>
      <%= f.submit "Publish", class: "button is-primary has-text-white is-fullwidth" %>
    <% end %>
  <% end %>
  <br>
  <%= link_to 'Delete listing', room_path(@room),
              method: :delete,
              data: { confirm: 'Are you sure to delete this listing ?' },
              class: "button is-danger has-text-white is-fullwidth" %>
</aside>

app/views/rooms/amenities.html.erb
<div class="columns">
    <div class="column is-one-quarter">
        <%= render  "room_menu" %>
    </div>
    <div class="column is-three-quarters">
        <div class="panel">
            <div class="panel-heading has-background-primary has-text-white has-text-weight-bold">
                Amenities
            </div>
            <div class="panel-block">
                <div class="container">
                    <div class="columns is-centered is-multiline">
                        <div class="column is-4 has-text-centered">
                            <%= form_for @room do |f| %>
                                <div class="checkbox">
                                    <%= f.check_box :is_tv %> TV
                                </div>
                        </div>
                        <div class="column is-4 has-text-centered">
                            <div class="checkbox">
                                <%= f.check_box :is_kitchen %> Kitchen
                            </div>
                        </div>
                        <div class="column is-4 has-text-centered">
                            <div class="checkbox">
                                <%= f.check_box :is_internet %> Internet
                            </div>
                        </div>
                        <div class="column is-4 has-text-centered">
                            <div class="checkbox">
                                <%= f.check_box :is_heating %> Heating
                            </div>
                        </div>
                        <div class="column is-4 has-text-centered">
                            <div class="checkbox">
                                <%= f.check_box :is_air %> Air conditionning
                            </div>
                        </div>
                        <div class="column is-4 has-text-centered">
                            <%= f.submit "Save", class: "button is-success" %>
                        </div>
                            <% end %>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

app/views/rooms/create.html.erb
<h1>Room#create</h1>
<p>Find me in app/views/room/create.html.erb</p>

app/views/rooms/description.html.erb
<div class="columns">
    <div class="column is-one-quarter">
        <%= render  "room_menu" %>
    </div>
    <div class="column is-three-quarters">
        <div class="panel">
            <div class="panel-heading has-background-primary has-text-white has-text-weight-bold">
                Description
            </div>
            <div class="panel-block">
                <div class="container">
                    <div class="columns is-centered">
                        <div class="column is-6">
                            <%= form_for @room do |f| %>
                                <div class="field has-text-centered">
                                    <%= f.label :listing_name, class: "label" %>
                                    <div class="control has-text-centered">
                                        <%= f.text_field :listing_name, placeholder: "My room", class: "input is-medium is-primary" %>
                                    </div>
                                </div>
                                <div class="field has-text-centered">
                                    <%= f.label :summary, class: "label" %>
                                    <div class="control has-text-centered">
                                        <%= f.text_area :summary,rows: 5, placeholder: "Summary of your house", class: "textarea is-medium is-primary" %>
                                    </div>
                                </div>
                                <div class="has-text-centered">
                                    <%= f.submit "Save", class: "button is-success" %>
                                </div>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

app/views/rooms/index.html.erb
<div class="columns">
    <div class="column is-one-quarter">
        <aside class="menu">
        <ul class="menu-list">
            <li> <%= link_to "Your Listings", rooms_path %> </li>
            <li> <%= link_to "Your Reservations", reservations_path %> </li>
            <li> <%= link_to "Your trips", trips_path %> </li>
        </ul>
        </aside>
    </div>
    <div class="column is-three-quarters">
        <div class="panel">
            <div class="panel-heading has-background-primary has-text-white has-text-weight-bold">
                Listings
            </div>
            <div class="panel-block">
                <div class="container">
                    <% @rooms.each do |room| %>
                        <div class="columns is-vcentered is-mobile">
                            <div class="column is-2 is-hidden-mobile">
                                <%= image_tag url_for(room.room_pictures.first), onerror: "this.src='http://contrapoderweb.com/wp-content/uploads/2014/10/default-img.gif'" %>
                            </div>
                            <div class="column is-5-desktop is-4-mobile">
                                <p class="is-size-5"><%= room.listing_name %></p>
                            </div>
                            <div class="column is-2-desktop is-3-mobile">
                                <%= link_to "Update", listing_room_path(room), class: "button is-primary has-text-white" %>
                            </div>
                            <div class="column is-3 has-text-right">
                                <% if room.active? %>
                                    <span class="tag is-success">status: published</span>
                                <% else %>
                                    <span class="tag is-light">status: unpublished</span>
                                <% end %>
                            </div>
                        </div>
                    <% end %>
                    <div class="has-text-centered">
                        <%= link_to "Create new listing", new_room_path, class: "button is-primary has-text-white" %>                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/rooms/listing.html.erb
<div class="columns">
    <div class="column is-one-quarter">
        <%= render  "room_menu" %>
    </div>
    <div class="column is-three-quarters">
        <div class="panel">
            <div class="panel-heading has-background-primary has-text-white has-text-weight-bold">
                Listing
            </div>
            <div class="panel-block">
                <div class="container">
                                    <%= form_for @room do |f| %>
            <div class="columns is-multiline">
                <div class="column is-one-third">
                    <div class="field has-text-centered">
                        <%= f.label :home_type, class: "label" %>
                        <div class="control has-text-centered">
                            <%= f.select    :home_type, [["Apartment", "Apartment"], ["House", "House"], ["Bed & Breakfast", "Bed & Breakfast"]],
                                             {prompt: "Select..."}, {class: "select is-medium is-primary", id: "home_type"} %>
                        </div>
                    </div>
                </div>
                <div class="column is-one-third has-text-centered">
                    <div class="field has-text-centered">
                        <%= f.label :room_type, class: "label" %>
                        <div class="control has-text-centered">
                            <%= f.select    :room_type, [["Entire", "Entire"], ["Private", "Private"], ["Shared", "Shared"]],
                                             {prompt: "Select..."}, {class: "select is-medium is-primary", id: "room_type"} %>
                        </div>
                    </div>
                </div>
                <div class="column is-one-third has-text-centered">
                    <div class="field has-text-centered">
                        <%= f.label :accommodate, class: "label" %>
                        <div class="control has-text-centered">
                            <%= f.select    :accommodate, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                                             {prompt: "Select..."}, {class: "select is-medium is-primary", id: "accommodate"} %>
                        </div>
                    </div>
                </div>
                <div class="column is-one-third has-text-centered">
                    <div class="field has-text-centered">
                        <%= f.label :bed_room, class: "label" %>
                        <div class="control has-text-centered">
                            <%= f.select    :bed_room, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                                             {prompt: "Select..."}, {class: "select is-medium is-primary", id: "bed_room"} %>
                        </div>
                    </div>
                </div>
                <div class="column is-one-third has-text-centered">
                    <div class="field has-text-centered">
                        <%= f.label :bath_room, class: "label" %>
                        <div class="control has-text-centered">
                            <%= f.select    :bath_room, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                                             {prompt: "Select..."}, {class: "select is-medium is-primary", id: "bath_room"} %>
                        </div>
                    </div>
                </div>
                <div class="column is-one-third has-text-centered">
                    <%= f.submit "Save", class: "button is-success is-medium" %>
                </div>
            </div>
            <% end %>
                </div>
            </div>
        </div>

    </div>
</div>

app/views/rooms/location.html.erb
<div class="columns">
    <div class="column is-one-quarter">
        <%= render  "room_menu" %>
    </div>
    <div class="column is-three-quarters">
        <div class="panel">
            <div class="panel-heading has-background-primary has-text-white has-text-weight-bold">
                Location
            </div>
            <div class="panel-block">
                <div class="container">
                    <div class="columns is-centered">
                        <div class="column is-6">
                            <%= form_for @room do |f| %>
                                <div class="field has-text-centered">
                                    <%= f.label :address, class: "label" %>
                                    <div class="control has-text-centered">
                                        <%= f.text_field :address, placeholder: "Your address", class: "textarea is-primary" %>
                                    </div>
                                </div>
                                <div class="has-text-centered">
                                    <%= f.submit "Save", class: "button is-success" %>
                                </div>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

app/views/rooms/photo_upload.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-carousel@4.0.4/dist/css/bulma-carousel.min.css">
<div class="columns">
    <div class="column is-one-quarter">
        <%= render  "room_menu" %>
    </div>
    <div class="column is-three-quarters">
        <div class="panel">
            <div class="panel-heading has-background-primary has-text-white has-text-weight-bold">
                Photos
            </div>
            <div class="panel-block">
                <div class="container">
                    <%= form_for @room do |f| %>
                    <div class="file is-centered">
                    <br><br>
                    <label class="file-label">
                        <%= f.file_field :room_pictures, accept:'image/*', required: true, onchange: "this.form.submit();" %>                        
                        <span class="file-cta">
                        <span class="file-icon">
                            <i class="fa fa-upload"></i>
                        </span>
                        <span class="file-label">
                            Upload a new picture
                        </span>
                        </span>
                    </label>
                    </div>
                    <% end %>
                    <% if @room.room_pictures.any? %>
                        <!-- Start Hero Carousel -->
                        <section class="hero is-medium has-carousel">
                            <div id="carousel-demo" class="hero-carousel">
                                <% @room.room_pictures.each_with_index do |picture, index| %>
                                    <div class=<%= "has-text-centered item-" + (index + 1).to_s %> >
                                        <%= link_to delete_image_attachment_room_url(picture.id), method: :delete, class: "button is-danger is-outlined has-text-danger" do %>
                                            <span class='icon is-small'><i class='fa fa-trash'></i></span> &nbsp;Delete picture
                                        <% end %>
                                        <%= image_tag url_for(picture) %>
                                    </div>
                                <% end %>
                            </div>
                            <div class="hero-head"></div>
                            <div class="hero-body"></div>
                            <div class="hero-foot"></div>
                        </section>
                        <!-- End Hero Carousel -->
                    <% else %>
                        <article class="message is-info">
                            <div class="message-body">
                                Please upload a picture on your room
                            </div>
                        </article>
                    <% end %>
                    </div>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bulma-carousel@4.0.4/dist/js/bulma-carousel.min.js"></script>
    <script>
    // Initialize all div with carousel class
    bulmaCarousel.attach('#carousel-demo', {
				slidesToScroll: 1,
				slidesToShow: 1
			})
    var options
    var carousels = bulmaCarousel.attach('.carousel', options);

    // Loop on each carousel initialized
    for(var i = 0; i < carousels.length; i++) {
        // Add listener to  event
        carousels[i].on('before:show', state => {
            console.log(state);
        });
    }

    // Access to bulmaCarousel instance of an element
    var element = document.querySelector('#my-element');
    if (element && element.bulmaCarousel) {
        // bulmaCarousel instance is available as element.bulmaCarousel
        element.bulmaCarousel.on('before-show', function(state) {
            console.log(state);
        });
    }
</script>

app/views/rooms/pricing.html.erb
<div class="columns">
    <div class="column is-one-quarter">
        <%= render  "room_menu" %>
    </div>
    <div class="column is-three-quarters">
        <div class="panel">
            <div class="panel-heading has-background-primary has-text-white has-text-weight-bold">
                Pricing
            </div>
            <div class="panel-block">
                <div class="container">
                    <div class="columns is-centered">
                        <div class="column is-2">
                            <%= form_for @room do |f| %>
                                <div class="field has-text-centered">
                                    <%= f.label :price, class: "label" %>
                                    <div class="control has-icons-right has-text-centered">
                                        <%= f.number_field :price, placeholder: "100$", class: "input is-primary" %>
                                        <span class="icon is-small is-right">
                                            <i class="fa fa-euro"></i>
                                        </span>
                                    </div>
                                </div>
                                <div class="has-text-centered">
                                    <%= f.submit "Save", class: "button is-success" %>
                                </div>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

app/views/rooms/update.html.erb
<h1>Room#update</h1>
<p>Find me in app/views/room/update.html.erb</p>